### PR TITLE
Rebase on Alpine

### PR DESCRIPTION
**Pull request by Jasper-Ben**
Benefits:
- Small image (~8MB)
- Easily (re)build with specific wireguard and babeld version
- Kernel module installed as dkms package
- Easy to install

Downsides/TODO:
- Not tested yet (build successful though, so that's something)
- Some submodules are currently built against git master branches, not sure how stable?
- lots more, I'm sure!

### CODE REVIEW

**Comment by penguineer** [comment]
It would be cool if these commits were not on the master branch, so that the commit sets and the merge can be seen later.

**Comment by Jasper-Ben** [comment]
Alright, I can recreate a merge request on a different branch. I didn't see it as a problem at the time, since last time we spoke you hadn't (to my understanding) tested the Debian container yet either.

**Comment by Jasper-Ben** [comment]
You might want to create an alpine branch here, so we can keep them separate for now. AFAIK I can only open a pull request on an existing branch in upstream.

**Comment by penguineer** [comment]
Done.

**Pull request closed without merging**
