### PR TITLE
Rebase on Alpine container

### PR DESCRIPTION
**Pull request by Jasper-Ben**
Benefits:
- Small image (~8MB)
- Easily (re)build with specific wireguard and babeld version
- Kernel module installed as dkms package
- Easy to install

TODO:

- [ ] Not tested yet (build successful though, so that's something)
- [ ] Some sub-modules are currently built against git master branches, not sure how stable?
- [ ] Install script currently doesn't remove older wireguard kernel modules automatically. Discuss: Is this desired or should this be changed?
-  lots more, I'm sure!

### CODE REVIEW

**Comment by christf** [comment]
wg quick should not be required. wg-broker-server has a couple of dependencies too:
socat and ip6tables should be there.

For babeld, the code is raised as PR's against jech's repository.

How exactly will the re-build of wireguard happen when the kernel changed?

**Comment by Jasper-Ben** [comment]
- wg-quick is used in the current run.sh at line 60.

- I will add socat and ip6tables to the installed packages

- I will change the Dockerfile to pull babeld from your docker fork for now.

- To my understanding the only thing that needs to be rebuilt on kernel changes is the wireguard kernel module. The install.sh script installs the module via dkms on the host, so this will automatically rebuild on kernel changes. The container itself should not be affected, since it uses the hosts shared kernel.
> Containers interact with the kernel through system calls and don't include any part of the kernel or the kernel modules inside the container. [...] The module needs to be loaded on your host OS, and not from the docker container.
https://stackoverflow.com/questions/33013539/docker-loading-kernel-modules

**Comment by Jasper-Ben** [comment]
One thing to keep in mind while testing: The current Alpine container only has sh installed. I'm not sure if the scripts running from entrypoint need bash.

**Comment by 24367dfa** [comment]
discarded, we will not rebase onto alpine

**Pull request closed without merging**
